version: '3.8'

services:
    localstack:
        container_name: "localstack_poc"
        image: localstack/localstack:latest
        environment: 
            - SERVICES=s3
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DEFAULT_REGION=us-east-2
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data
            - PORT_WEB_UI=8080
            - LAMBDA_DOCKER_NETWORK=localstack-tutorial
        ports:
            - "443:443"
            - "4566:4566"
            - "4571:4571"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - localstack_data:/tmp/localstack/data
volumes:
    localstack_data:
networks:
    default:
        external:
            name: localstack-tutorial